import { Inter } from "next/font/google";
import "./globals.css";
import Head from 'next/head';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "CodingQuizHub",
  description: "Generated by Coding Quiz Hub",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <Head>
        <link rel="icon" href="/favicon.ico" sizes="32x32" />
        <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-2530221297315413"
          crossorigin="anonymous"></script>
        <meta name="description" content="Generated by Coding Quiz Hub" />
        <meta name="keywords" content="HTML,CSS,JavaScript,React.js, Next.js, Node.js,Php,MySQL,Angular,Python,java,dotnet,mongodb,coding,programing language,coding quiz," />
        <link rel="icon" type="image/png" href="/favicon.png" sizes="32x32" />

      </Head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
