import { Inter } from "next/font/google";
import "./globals.css";
import Head from 'next/head';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "CodingQuizHub",
  description: "Generated by Coding Quiz Hub",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <Head>
      <link rel="icon" href="/favicon.ico" sizes="32x32" />
        <meta name="description" content="Generated by Coding Quiz Hub" />
        <link rel="icon" type="image/png" href="/favicon.png" sizes="32x32"/>
     

      </Head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
