import { Inter } from "next/font/google";
import "./globals.css";
import Head from 'next/head';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "CodingQuizHub",
  description: "Generated by Coding Quiz Hub",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <Head>
        <link rel="icon" href="/favicon.ico" sizes="32x32" />
        <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-2530221297315413"
          crossorigin="anonymous"></script>
        <meta name="description" content="Generated by Coding Quiz Hub" />
        <meta name="keywords" content="HTML,CSS,JavaScript,React.js, Next.js, Node.js,Php,MySQL,Angular,Python,java,dotnet,mongodb,coding,programing language,coding quiz," />
        <link rel="icon" type="image/png" href="/favicon.png" sizes="32x32" />
        <meta name="google-adsense-account" content="ca-pub-2530221297315413" />
        <script
        strategy="afterInteractive"
        src={`https://www.googletagmanager.com/gtag/js?id=G-HZXCR9YV9R`}
      />
      <script async="async" data-cfasync="false" src="//pl25748529.profitablecpmrate.com/973da03438430a67f8d94d103c0bff91/invoke.js"></script>
      <div id="container-973da03438430a67f8d94d103c0bff91"></div>
<script type='text/javascript' src='//pl25748443.profitablecpmrate.com/98/09/fc/9809fc1c07e49792d271d009f521c87c.js'></script>
      <script id="google-analytics" strategy="afterInteractive">
        {`
          window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments);}
          gtag('js', new Date());
          gtag('config', 'G-HZXCR9YV9R');
        `}
      </script>
      </Head>
      <body className={inter.className}>{children}
      <script type='text/javascript' src='//pl25747768.profitablecpmrate.com/fe/b2/3c/feb23c23606b1f21baabeb52d82aa42f.js'></script>
      
      
      </body>
    </html>
  );
}
